######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 10 00:59:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . vcc
INCLUDEPATH += . vcc

# Input
HEADERS += vcc/helpers.h vcc/main_window.hpp
FORMS += vcc/main_window.ui
SOURCES += vcc/helpers.c vcc/main_window.cpp vcc/vaio-control-center.cpp
